{
    'name': 'Petty Cash Management',
    'version': '18.0.0.1.0',
    'category': 'Accounting',
    'summary': 'Manage petty cash requests with multi-level approval',
    'author': 'MOB: Ayanfe',
    'depends': ['account', 'analytic', 'mail', 'base_automation'],
    'data': [
        'security/petty_cash_security.xml',
        'security/ir.model.access.csv',
        'views/res_company_views.xml',
        'data/email_templates.xml',
        'data/automated_actions.xml',
        'views/petty_cash_request_views.xml',
        'views/division_float_views.xml',
        'views/account_analytic_account_views.xml',
    ],
    'images': 'static/description/icon.png',
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'price': 200.0,
    'currency': 'USD',
}
