{
    'name': 'Petty Cash Management',
    'version': '19.0.0.1.0',
    'category': 'Accounting',
    'summary': 'Manage petty cash requests with multi-level approval.',
    'author': 'Tech Joe',
    'depends': ['account', 'analytic', 'accountant', 'mail', 'base_automation'],
    'data': [
        'security/petty_cash_security.xml',
        'security/ir.model.access.csv',
        'views/res_company_views.xml',
        'data/email_templates.xml',
        'data/automated_actions.xml',
        'views/petty_cash_request_views.xml',
        'views/division_float_views.xml',
        'views/account_analytic_account_views.xml',
    ],
    'images': ['static/description/banner.png'],
    'live_test_url': 'http://tech-joe.tech-joe.infinityfreeapp.com/helpdesk/customer-care-1',
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'price': 58.0,
    'currency': 'USD',
}
