from . import vehicle_brand
from . import vehicle_model
from . import vehicle_lot
from . import vehicle_commission_rule
from . import vehicle
from . import vehicle_sale
from . import vehicle_purchase
from . import vehicle_service
from . import vehicle_inspection
from . import vehicle_history
from . import res_partner
